version: "3.8"

services:
    francis-nginx:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8977:80"
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html

    database:
        image: mariadb
        restart: always
        volumes:
            - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_DATABASE: php_db
            MYSQL_ROOT_PASSWORD: password

    adminer:
        image: adminer
        restart: always
        ports:
            - "1334:8080"
